[project]
name = "handwrite"
version = "0.1.0"
description = "本项目为解决一些大学无用手写作业"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "handright>=8.2.0",
    "pyside6>=6.9.0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
dist = [
    "pyinstaller>=6.13.0",
]
